// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyEmpi2EAVZNtkTi0y02VEPLr5wd0rzI',
    appId: '1:514378549092:web:5a199dad59f4ac6f1d9c71',
    messagingSenderId: '514378549092',
    projectId: 'bookswap-751e6',
    authDomain: 'bookswap-751e6.firebaseapp.com',
    storageBucket: 'bookswap-751e6.firebasestorage.app',
    measurementId: 'G-S78HSPXPS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqobgLIB4C2YlR7Q5v-NB7Lab66th0Mo',
    appId: '1:514378549092:android:2a945f2ab7a56abe1d9c71',
    messagingSenderId: '514378549092',
    projectId: 'bookswap-751e6',
    storageBucket: 'bookswap-751e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQfMNTUbd6QIORJ3v8Pl_OxdFJZBD38Q',
    appId: '1:514378549092:ios:3d4301087779e8021d9c71',
    messagingSenderId: '514378549092',
    projectId: 'bookswap-751e6',
    storageBucket: 'bookswap-751e6.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQfMNTUbd6QIORJ3v8Pl_OxdFJZBD38Q',
    appId: '1:514378549092:ios:3d4301087779e8021d9c71',
    messagingSenderId: '514378549092',
    projectId: 'bookswap-751e6',
    storageBucket: 'bookswap-751e6.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVyEmpi2EAVZNtkTi0y02VEPLr5wd0rzI',
    appId: '1:514378549092:web:627906718cfedf031d9c71',
    messagingSenderId: '514378549092',
    projectId: 'bookswap-751e6',
    authDomain: 'bookswap-751e6.firebaseapp.com',
    storageBucket: 'bookswap-751e6.firebasestorage.app',
    measurementId: 'G-SKG8CJR1BK',
  );

}